services:
  - type: web
    name: laravel-portfolio
    runtime: docker
    repo: https://github.com/Matrixxboy/portfolio
    buildCommand: "./.render-build.sh"
    startCommand: "php artisan serve --host=0.0.0.0 --port=$PORT"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: sqlite
